from __future__ import annotations

import html
import re
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


_TRACKING_QUERY_KEYS = {
    "fbclid",
    "gclid",
    "dclid",
    "msclkid",
    "mc_cid",
    "mc_eid",
    "ocid",
}
_PARENTHETICAL_MARKDOWN_LINK_RE = re.compile(
    r"\s*\(\s*\[[^\]]*]\(\s*https?://[^)]+\)\s*\)",
    flags=re.IGNORECASE,
)
_MARKDOWN_IMAGE_RE = re.compile(
    r"!\[([^\]]*)]\(\s*https?://[^)]+\)",
    flags=re.IGNORECASE,
)
_MARKDOWN_LINK_RE = re.compile(
    r"\[([^\]]+)]\(\s*https?://[^)]+\)",
    flags=re.IGNORECASE,
)
_HTML_ANCHOR_RE = re.compile(
    r"<a\b[^>]*>(.*?)</a>",
    flags=re.IGNORECASE | re.DOTALL,
)
_RAW_URL_RE = re.compile(
    r"<?https?://[^\s<>\])}]+>?",
    flags=re.IGNORECASE,
)
_PROCESS_DISCLOSURE_PATTERNS = (
    (
        re.compile(
            r"\b(?:AI|artificial intelligence)[ -](?:generated|written|created|produced)\b",
            flags=re.IGNORECASE,
        ),
        "",
    ),
    (
        re.compile(
            r"\bgenerated by (?:an?\s+)?(?:AI|artificial intelligence|language model)\b",
            flags=re.IGNORECASE,
        ),
        "",
    ),
    (
        re.compile(
            r"\bAI\s+(?=(?:analysis|review|summary|content|response|assistant|model|system)\b)",
            flags=re.IGNORECASE,
        ),
        "",
    ),
    (
        re.compile(
            r"\baccording to (?:OpenAI|ChatGPT|an? AI (?:system|model|assistant))\b[:,]?\s*",
            flags=re.IGNORECASE,
        ),
        "",
    ),
)


def _plain_link_label(match: re.Match[str]) -> str:
    label = match.group(1).strip()
    if re.fullmatch(
        r"(?:www\.)?[a-z0-9.-]+\.[a-z]{2,}(?:/[^\s]*)?",
        label,
        flags=re.IGNORECASE,
    ):
        return ""
    return label


def sanitize_public_text(value: str | None) -> str:
    """Return plain public-facing prose without links or process disclosures."""
    text = html.unescape(str(value or ""))
    if not text.strip():
        return ""
    text = _PARENTHETICAL_MARKDOWN_LINK_RE.sub("", text)
    text = _MARKDOWN_IMAGE_RE.sub(r"\1", text)
    text = _MARKDOWN_LINK_RE.sub(_plain_link_label, text)
    text = _HTML_ANCHOR_RE.sub(r"\1", text)
    text = _RAW_URL_RE.sub("", text)
    for pattern, replacement in _PROCESS_DISCLOSURE_PATTERNS:
        text = pattern.sub(replacement, text)
    text = re.sub(r"\(\s*\)", "", text)
    text = re.sub(r"\[\s*]", "", text)
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    text = re.sub(r"([(\[])\s+", r"\1", text)
    text = re.sub(r"\s+([)\]])", r"\1", text)
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = re.sub(r"\s*\n\s*", " ", text)
    return text.strip(" \t\r\n-–—,;:")


def sanitize_public_url(value: str | None) -> str | None:
    """Remove marketing/tracking parameters without changing the destination."""
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        parsed = urlsplit(raw)
    except ValueError:
        return raw
    if parsed.scheme.lower() not in {"http", "https"} or not parsed.netloc:
        return raw
    query = urlencode(
        [
            (key, item)
            for key, item in parse_qsl(parsed.query, keep_blank_values=True)
            if not key.lower().startswith("utm_")
            and key.lower() not in _TRACKING_QUERY_KEYS
        ],
        doseq=True,
    )
    return urlunsplit(
        (
            parsed.scheme.lower(),
            parsed.netloc.lower(),
            parsed.path,
            query,
            "",
        )
    )


def public_location_hint(hint: dict) -> dict:
    """Keep only fields that belong to the external location contract."""
    return {
        key: hint.get(key)
        for key in (
            "name",
            "country_code",
            "latitude",
            "longitude",
            "confidence",
        )
        if hint.get(key) is not None
    }
